# Generated by Django 2.2.16 on 2021-05-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PDAQ_hdtest', '0001_initial'),
        ('Custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='出厂日期')),
                ('camera_model', models.PositiveIntegerField(choices=[(4, '环视（04）'), (5, '后视（05）'), (6, 'BSD（06）'), (3, '相机+前视（03）'), (1, '相机模式（01）'), (2, '前视模式（02）')], default=1, verbose_name='相机模式')),
                ('Serial_number', models.CharField(max_length=50, unique=True, verbose_name='序列号')),
                ('unique_serial', models.CharField(max_length=5, unique=True, verbose_name='唯一序列号')),
                ('resolution', models.CharField(blank=True, default='1280x1080', max_length=10, null=True, verbose_name='相机分辨率')),
                ('camera_num', models.CharField(blank=True, default=6, max_length=3, null=True, verbose_name='相机数量')),
                ('image_format', models.CharField(blank=True, default='YUYV', max_length=10, null=True, verbose_name='图像格式')),
                ('program_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='程序版本')),
                ('IP_address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='PDAQ_hdtest.PDAQ_hd', verbose_name='IP地址')),
                ('custom', models.OneToOneField(db_constraint=False, on_delete=False, related_name='custom', to='Custom.Custom', verbose_name='客户')),
            ],
            options={
                'verbose_name': '软件配置信息',
                'verbose_name_plural': '软件配置信息',
            },
        ),
    ]
