# Generated by Django 2.2.16 on 2021-05-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_message',
            name='IP_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ip_address', to='PDAQ_hdtest.PDAQ_hd', verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='config_message',
            name='camera_model',
            field=models.PositiveIntegerField(choices=[(6, 'BSD（06）'), (3, '相机+前视（03）'), (2, '前视模式（02）'), (5, '后视（05）'), (1, '相机模式（01）'), (4, '环视（04）')], default=1, verbose_name='相机模式'),
        ),
        migrations.AlterField(
            model_name='config_message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出厂日期'),
        ),
    ]
