# Generated by Django 2.2.16 on 2021-05-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_message', '0003_auto_20210528_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_message',
            name='camera_model',
            field=models.PositiveIntegerField(choices=[(2, '前视模式（02）'), (1, '相机模式（01）'), (4, '环视（04）'), (6, 'BSD（06）'), (3, '相机+前视（03）'), (5, '后视（05）')], default=1, verbose_name='相机模式'),
        ),
        migrations.AlterField(
            model_name='config_message',
            name='custom',
            field=models.ForeignKey(db_constraint=False, on_delete=False, related_name='custom', to='Custom.Custom', verbose_name='客户'),
        ),
    ]
