# Generated by Django 2.2.16 on 2021-05-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_message', '0009_auto_20210531_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_message',
            name='camera_model',
            field=models.PositiveIntegerField(choices=[(6, 'BSD（06）'), (5, '后视（05）'), (1, '相机模式（01）'), (2, '前视模式（02）'), (4, '环视（04）'), (3, '相机+前视（03）')], default=1, verbose_name='相机模式'),
        ),
    ]
