# Generated by Django 2.2.16 on 2021-05-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_message', '0011_auto_20210531_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_message',
            name='camera_model',
            field=models.PositiveIntegerField(choices=[(3, '相机+前视（03）'), (5, '后视（05）'), (6, 'BSD（06）'), (2, '前视模式（02）'), (1, '相机模式（01）'), (4, '环视（04）')], default=1, verbose_name='相机模式'),
        ),
    ]
