# Generated by Django 2.2.16 on 2021-06-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_message', '0014_auto_20210601_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_message',
            name='camera_model',
            field=models.IntegerField(choices=[(2, '前视模式（02）'), (5, '后视（05）'), (1, '相机模式（01）'), (4, '环视（04）'), (6, 'BSD（06）'), (3, '相机+前视（03）')], default=1, verbose_name='相机模式'),
        ),
    ]
