# Generated by Django 2.2.16 on 2021-07-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_message', '0015_auto_20210607_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_message',
            name='product_name',
            field=models.IntegerField(choices=[(1, 'calmcar'), (2, 'vbox')], default=2, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='config_message',
            name='product_status',
            field=models.IntegerField(choices=[(1, '生产模式'), (2, '测试'), (3, '开发模式')], default=1, verbose_name='产品状态'),
        ),
        migrations.AlterField(
            model_name='config_message',
            name='camera_model',
            field=models.IntegerField(choices=[(3, '相机+前视（03）'), (2, '前视模式（02）'), (4, '环视（04）'), (6, 'BSD（06）'), (5, '后视（05）'), (1, '相机模式（01）')], default=1, verbose_name='相机模式'),
        ),
        migrations.AlterField(
            model_name='config_message',
            name='custom',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='Custom.Custom', verbose_name='客户'),
        ),
    ]
