# Generated by Django 2.2.16 on 2021-07-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_message', '0017_auto_20210703_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_message',
            name='camera_model',
            field=models.IntegerField(choices=[(6, 'BSD（06）'), (5, '后视（05）'), (1, '相机模式（01）'), (2, '前视模式（02）'), (3, '相机+前视（03）'), (4, '环视（04）')], default=1, verbose_name='相机模式'),
        ),
    ]
