# Generated by Django 2.2.16 on 2021-07-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_message', '0018_auto_20210705_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_message',
            name='online_status',
            field=models.CharField(blank=True, default='离线', max_length=10, null=True, verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='config_message',
            name='camera_model',
            field=models.IntegerField(choices=[(1, '相机模式（01）'), (5, '后视（05）'), (3, '相机+前视（03）'), (6, 'BSD（06）'), (2, '前视模式（02）'), (4, '环视（04）')], default=1, verbose_name='相机模式'),
        ),
        migrations.AlterField(
            model_name='config_message',
            name='product_name',
            field=models.IntegerField(choices=[(2, 'vbox'), (1, 'calmcar')], default=2, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='config_message',
            name='product_status',
            field=models.IntegerField(choices=[(3, '开发模式'), (1, '生产模式'), (2, '测试')], default=1, verbose_name='产品状态'),
        ),
    ]
